=begin
#MF KESSAI API v2

#MF KESSAI REST API

The version of the OpenAPI document: 0.2.0
Contact: support@mfkessai.co.jp
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.1

=end

require 'date'

module OpenapiClient
  # 非課税の控除金額とその内訳です。手数料と早期振込手数料が非課税となります。
  class DeductionTaxFree
    # 非課税の控除金額です。
    attr_accessor :amount

    # 手数料の金額です。
    attr_accessor :commission_amount

    # 早期振込手数料の金額です。
    attr_accessor :early_payout_commission_amount

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'amount' => :'amount',
        :'commission_amount' => :'commission_amount',
        :'early_payout_commission_amount' => :'early_payout_commission_amount'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'amount' => :'Integer',
        :'commission_amount' => :'Integer',
        :'early_payout_commission_amount' => :'Integer'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::DeductionTaxFree` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::DeductionTaxFree`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'commission_amount')
        self.commission_amount = attributes[:'commission_amount']
      end

      if attributes.key?(:'early_payout_commission_amount')
        self.early_payout_commission_amount = attributes[:'early_payout_commission_amount']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if !@amount.nil? && @amount > 2147483647
        invalid_properties.push('invalid value for "amount", must be smaller than or equal to 2147483647.')
      end

      if !@amount.nil? && @amount < 0
        invalid_properties.push('invalid value for "amount", must be greater than or equal to 0.')
      end

      if !@commission_amount.nil? && @commission_amount > 2147483647
        invalid_properties.push('invalid value for "commission_amount", must be smaller than or equal to 2147483647.')
      end

      if !@commission_amount.nil? && @commission_amount < 0
        invalid_properties.push('invalid value for "commission_amount", must be greater than or equal to 0.')
      end

      if !@early_payout_commission_amount.nil? && @early_payout_commission_amount > 2147483647
        invalid_properties.push('invalid value for "early_payout_commission_amount", must be smaller than or equal to 2147483647.')
      end

      if !@early_payout_commission_amount.nil? && @early_payout_commission_amount < 0
        invalid_properties.push('invalid value for "early_payout_commission_amount", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@amount.nil? && @amount > 2147483647
      return false if !@amount.nil? && @amount < 0
      return false if !@commission_amount.nil? && @commission_amount > 2147483647
      return false if !@commission_amount.nil? && @commission_amount < 0
      return false if !@early_payout_commission_amount.nil? && @early_payout_commission_amount > 2147483647
      return false if !@early_payout_commission_amount.nil? && @early_payout_commission_amount < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] amount Value to be assigned
    def amount=(amount)
      if !amount.nil? && amount > 2147483647
        fail ArgumentError, 'invalid value for "amount", must be smaller than or equal to 2147483647.'
      end

      if !amount.nil? && amount < 0
        fail ArgumentError, 'invalid value for "amount", must be greater than or equal to 0.'
      end

      @amount = amount
    end

    # Custom attribute writer method with validation
    # @param [Object] commission_amount Value to be assigned
    def commission_amount=(commission_amount)
      if !commission_amount.nil? && commission_amount > 2147483647
        fail ArgumentError, 'invalid value for "commission_amount", must be smaller than or equal to 2147483647.'
      end

      if !commission_amount.nil? && commission_amount < 0
        fail ArgumentError, 'invalid value for "commission_amount", must be greater than or equal to 0.'
      end

      @commission_amount = commission_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] early_payout_commission_amount Value to be assigned
    def early_payout_commission_amount=(early_payout_commission_amount)
      if !early_payout_commission_amount.nil? && early_payout_commission_amount > 2147483647
        fail ArgumentError, 'invalid value for "early_payout_commission_amount", must be smaller than or equal to 2147483647.'
      end

      if !early_payout_commission_amount.nil? && early_payout_commission_amount < 0
        fail ArgumentError, 'invalid value for "early_payout_commission_amount", must be greater than or equal to 0.'
      end

      @early_payout_commission_amount = early_payout_commission_amount
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          amount == o.amount &&
          commission_amount == o.commission_amount &&
          early_payout_commission_amount == o.early_payout_commission_amount
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [amount, commission_amount, early_payout_commission_amount].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        OpenapiClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
