=begin
#MF KESSAI API v2

#MF KESSAI REST API

The version of the OpenAPI document: 0.2.0
Contact: support@mfkessai.co.jp
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.1

=end

require 'date'

module OpenapiClient
  class TaxIncludedType
    INCLUDED = "included".freeze
    EXCLUDED = "excluded".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = TaxIncludedType.constants.select { |c| TaxIncludedType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #TaxIncludedType" if constantValues.empty?
      value
    end
  end
end
