=begin
#MF KESSAI REST API

#MF KESSAI REST API

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require "uri"

module SwaggerClient
  class DestinationApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # create destination
    # 請求先を登録
    # @param payload 
    # @param [Hash] opts the optional parameters
    # @return [MfkDestination]
    def destination_create(payload, opts = {})
      data, _status_code, _headers = destination_create_with_http_info(payload, opts)
      return data
    end

    # create destination
    # 請求先を登録
    # @param payload 
    # @param [Hash] opts the optional parameters
    # @return [Array<(MfkDestination, Fixnum, Hash)>] MfkDestination data, response status code and response headers
    def destination_create_with_http_info(payload, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: DestinationApi.destination_create ..."
      end
      # verify the required parameter 'payload' is set
      if @api_client.config.client_side_validation && payload.nil?
        fail ArgumentError, "Missing the required parameter 'payload' when calling DestinationApi.destination_create"
      end
      # resource path
      local_var_path = "/destinations"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/vnd.goa.error', 'application/vnd.mfk.destination', 'application/vnd.goa.error', 'application/vnd.goa.error', 'application/vnd.goa.error'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json', 'application/xml', 'application/gob', 'application/x-gob'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(payload)
      auth_names = ['apikey']
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'MfkDestination')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: DestinationApi#destination_create\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
