=begin
#MF KESSAI API v2

#MF KESSAI REST API

The version of the OpenAPI document: 0.2.0
Contact: support@mfkessai.co.jp
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::BillingApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BillingApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::BillingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BillingApi' do
    it 'should create an instance of BillingApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::BillingApi)
    end
  end

  # unit tests for get_billing
  # 請求取得
  # @param billing_id 対象の請求IDを指定してください。
  # @param [Hash] opts the optional parameters
  # @return [Billing]
  describe 'get_billing test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_billings_list
  # 請求一覧取得
  # @param [Hash] opts the optional parameters
  # @option opts [String] :customer_id 任意の顧客IDを指定します。指定した顧客への請求が返却されます。
  # @option opts [Array<String>] :status 請求ステータスを指定します。該当するステータスの請求が返却されます。複数指定することが可能です。指定できる値は &#x60;scheduled&#x60;(請求予定), &#x60;invoice_issued&#x60;(請求書発行済), &#x60;account_transfer_notified&#x60;(口座振替通知済)の3種類のみです。
  # @option opts [String] :due_date_from 日付を指定します。指定した日付以降の支払期限となっている請求を取得できます。指定された日付のものも含まれます。
  # @option opts [String] :due_date_to 日付を指定します。指定した日付以前の支払期限となっている請求を取得できます。指定された日付のものも含まれます。
  # @option opts [String] :issue_date_from 日付を指定します。指定した日付以降の請求書発行日となっている請求を取得できます。指定された日付のものも含まれます。
  # @option opts [String] :issue_date_to 日付を指定します。指定した日付以前の請求書発行日となっている請求を取得できます。指定された日付のものも含まれます。
  # @option opts [Boolean] :unpaid 未入金のあり(&#x60;true&#x60;)、なし(&#x60;false&#x60;)を指定します。空文字が指定された場合、&#x60;false&#x60;として扱われます。
  # @option opts [String] :after 任意のリソースIDを指定します。追加日時の降順でこのIDのリソースよりも後のリソースを取得します。この時&#x60;after&#x60;で指定したIDのリソースは結果に含まれません。
  # @option opts [String] :before 任意のリソースIDを指定します。追加日時の降順でこのIDのリソースよりも前のリソースを取得します。この時&#x60;before&#x60;で指定したIDのリソースは結果に含まれません。
  # @option opts [Integer] :limit 取得したいリソースの最大件数を指定します。1~200の間の整数で指定してください。指定がない場合は20になります。
  # @return [InlineResponse2005]
  describe 'get_billings_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
