=begin
#MF KESSAI REST API

#MF KESSAI REST API

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for Mfkessai::CustomerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CustomerApi' do
  before do
    # run before each test
    @instance = Mfkessai::CustomerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomerApi' do
    it 'should create an instance of CustomerApi' do
      expect(@instance).to be_instance_of(Mfkessai::CustomerApi)
    end
  end

  # unit tests for customer_index
  # index customer
  # 顧客リストを取得
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page ページ番号
  # @option opts [Integer] :per_page 1ページあたりの件数
  # @return [MfkCustomers]
  describe 'customer_index test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customer_show
  # show customer
  # 顧客IDを指定して取得
  # @param id 顧客ID
  # @param [Hash] opts the optional parameters
  # @return [MfkCustomer]
  describe 'customer_show test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
