=begin
#MF KESSAI API v2

#MF KESSAI REST API

The version of the OpenAPI document: 0.2.0
Contact: support@mfkessai.co.jp
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::CustomerExaminationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomerExaminationApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::CustomerExaminationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomerExaminationApi' do
    it 'should create an instance of CustomerExaminationApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::CustomerExaminationApi)
    end
  end

  # unit tests for create_customer_examination
  # 顧客を指定して顧客審査を申請することができます。申請後2営業日以内に審査いたします。
  # 顧客審査申請
  # @param payload 顧客審査申請情報です。
  # @param [Hash] opts the optional parameters
  # @return [CustomerExamination]
  describe 'create_customer_examination test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_customer_examination
  # 顧客審査IDを指定して対象顧客審査１件を取得することができます。
  # 顧客審査取得
  # @param customer_examination_id 対象の顧客審査IDを指定してください。
  # @param [Hash] opts the optional parameters
  # @return [CustomerExamination]
  describe 'get_customer_examination test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_customer_examinations_list
  # 顧客審査の一覧を取得します。顧客IDやステータスで絞り込んで取得することもできます。
  # 顧客審査一覧取得
  # @param [Hash] opts the optional parameters
  # @option opts [String] :customer_id 顧客IDを指定します。指定された顧客に対する顧客審査を取得します。
  # @option opts [String] :status 顧客審査のステータスを指定します。未審査(&#x60;unexamined&#x60;)、審査通過(&#x60;passed&#x60;)、審査否決(&#x60;rejected&#x60;)のいずれかを指定してください。
  # @option opts [DateTime] :created_at_from 指定された日時以降に作成された請求先を取得します。指定された日時に作成されたものも含まれます。 RFC3399の&#x60;date-time&#x60;(2019-04-01T10:36:43+09:00)で指定してください。
  # @option opts [DateTime] :created_at_to 指定された日時以前に作成された請求先を取得します。指定された日時に作成されたものも含まれます。 RFC3399の&#x60;date-time&#x60;(2019-04-01T10:36:43+09:00)で指定してください。
  # @option opts [String] :after 任意のリソースIDを指定します。追加日時の降順でこのIDのリソースよりも後のリソースを取得します。この時&#x60;after&#x60;で指定したIDのリソースは結果に含まれません。
  # @option opts [String] :before 任意のリソースIDを指定します。追加日時の降順でこのIDのリソースよりも前のリソースを取得します。この時&#x60;before&#x60;で指定したIDのリソースは結果に含まれません。
  # @option opts [Integer] :limit 取得したいリソースの最大件数を指定します。1~200の間の整数で指定してください。指定がない場合は20になります。
  # @return [InlineResponse2002]
  describe 'get_customer_examinations_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
