=begin
#MF KESSAI API v2

#MF KESSAI REST API

The version of the OpenAPI document: 0.2.0
Contact: support@mfkessai.co.jp
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DestinationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DestinationApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DestinationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DestinationApi' do
    it 'should create an instance of DestinationApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DestinationApi)
    end
  end

  # unit tests for create_destination
  # 顧客を指定して請求先を登録することができます。
  # 請求先登録
  # @param payload 請求先登録情報です。
  # @param [Hash] opts the optional parameters
  # @return [Destination]
  describe 'create_destination test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_destination
  # 請求先IDを指定して対象請求先１件を取得することができます。
  # 請求先取得
  # @param destination_id 対象の請求先IDを指定してください。
  # @param [Hash] opts the optional parameters
  # @return [Destination]
  describe 'get_destination test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_destinations_list
  # 請求先の一覧を取得します。顧客IDや顧客番号で特定の顧客に紐づく請求先に絞り込んで取得することもできます。
  # 請求先一覧取得
  # @param [Hash] opts the optional parameters
  # @option opts [String] :customer_id 顧客IDを指定します。指定された顧客の請求先を取得します。&#x60;customer_number&#x60;に別の顧客の顧客番号を指定した場合には該当請求先は0件になります。
  # @option opts [String] :customer_number 顧客番号を指定します。指定された顧客の請求先を取得します。&#x60;customer_id&#x60;に別の顧客の顧客IDを指定した場合には該当請求先は0件になります。
  # @option opts [DateTime] :created_at_from 指定された日時以降に作成された請求先を取得します。指定された日時に作成されたものも含まれます。 RFC3399の&#x60;date-time&#x60;(2019-04-01T10:36:43+09:00)で指定してください。
  # @option opts [DateTime] :created_at_to 指定された日時以前に作成された請求先を取得します。指定された日時に作成されたものも含まれます。 RFC3399の&#x60;date-time&#x60;(2019-04-01T10:36:43+09:00)で指定してください。
  # @option opts [String] :after 任意のリソースIDを指定します。追加日時の降順でこのIDのリソースよりも後のリソースを取得します。この時&#x60;after&#x60;で指定したIDのリソースは結果に含まれません。
  # @option opts [String] :before 任意のリソースIDを指定します。追加日時の降順でこのIDのリソースよりも前のリソースを取得します。この時&#x60;before&#x60;で指定したIDのリソースは結果に含まれません。
  # @option opts [Integer] :limit 取得したいリソースの最大件数を指定します。1~200の間の整数で指定してください。指定がない場合は20になります。
  # @return [InlineResponse2001]
  describe 'get_destinations_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
