=begin
#MF KESSAI REST API

#MF KESSAI REST API

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ExaminationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ExaminationApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ExaminationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExaminationApi' do
    it 'should create an instance of ExaminationApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ExaminationApi)
    end
  end

  # unit tests for examination_create
  # create examination
  # 審査のための取引情報を登録
  # @param payload 
  # @param [Hash] opts the optional parameters
  # @return [MfkExamination]
  describe 'examination_create test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for examination_create_transaction
  # create_transaction examination
  # 審査時に登録した情報をもとに取引を登録
  # @param id 
  # @param payload 
  # @param [Hash] opts the optional parameters
  # @return [MfkTransaction]
  describe 'examination_create_transaction test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for examination_index
  # index examination
  # 審査リストを取得
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page ページ番号
  # @option opts [Integer] :per_page 1ページあたりの件数
  # @return [MfkExaminations]
  describe 'examination_index test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for examination_show
  # show examination
  # IDを指定して審査情報を取得
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [MfkExamination]
  describe 'examination_show test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
