=begin
#MF KESSAI API v2

#MF KESSAI REST API

The version of the OpenAPI document: 0.2.0
Contact: support@mfkessai.co.jp
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::PayoutApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PayoutApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::PayoutApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PayoutApi' do
    it 'should create an instance of PayoutApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::PayoutApi)
    end
  end

  # unit tests for get_payout
  # 振込取得
  # @param payout_id 対象の振込ID。
  # @param [Hash] opts the optional parameters
  # @return [Payout]
  describe 'get_payout test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_payouts_list
  # 振込一覧取得
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :status 振込ステータスを指定します。該当するステータスの振込が返却されます。指定できる値は &#x60;in_progress&#x60;(振込手続中), &#x60;completed&#x60;(振込完了)の2種類のみです。
  # @option opts [Date] :payout_date_from 日付を指定します。指定した日付以降の振込予定日となっている振込を取得できます。指定された日付のものも含まれます。
  # @option opts [Date] :payout_date_to 日付を指定します。指定した日付以前の振込予定日となっている振込を取得できます。指定された日付のものも含まれます。
  # @option opts [String] :after 任意のリソースIDを指定します。追加日時の降順でこのIDのリソースよりも後のリソースを取得します。この時&#x60;after&#x60;で指定したIDのリソースは結果に含まれません。
  # @option opts [String] :before 任意のリソースIDを指定します。追加日時の降順でこのIDのリソースよりも前のリソースを取得します。この時&#x60;before&#x60;で指定したIDのリソースは結果に含まれません。
  # @option opts [Integer] :limit 取得したいリソースの最大件数を指定します。1~200の間の整数で指定してください。指定がない場合は20になります。
  # @return [InlineResponse2006]
  describe 'get_payouts_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
