=begin
#MF KESSAI REST API

#MF KESSAI REST API

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for Mfkessai::PingApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PingApi' do
  before do
    # run before each test
    @instance = Mfkessai::PingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PingApi' do
    it 'should create an instance of PingApi' do
      expect(@instance).to be_instance_of(Mfkessai::PingApi)
    end
  end

  # unit tests for ping_show
  # show ping
  # Send ping to service
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'ping_show test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
