=begin
#MF KESSAI API v2

#MF KESSAI REST API

The version of the OpenAPI document: 0.2.0
Contact: support@mfkessai.co.jp
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::TransactionApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TransactionApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::TransactionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TransactionApi' do
    it 'should create an instance of TransactionApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::TransactionApi)
    end
  end

  # unit tests for cancel_transaction
  # 取引キャンセル
  # @param transaction_id 対象の取引IDを指定してください。
  # @param [Hash] opts the optional parameters
  # @return [Transaction]
  describe 'cancel_transaction test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_transaction
  # 取引登録
  # @param payload 
  # @param [Hash] opts the optional parameters
  # @return [Transaction]
  describe 'create_transaction test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_transaction
  # 取引取得
  # @param transaction_id 対象の取引IDを指定してください。
  # @param [Hash] opts the optional parameters
  # @return [Transaction]
  describe 'get_transaction test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_transactions_list
  # 取引一覧取得
  # @param [Hash] opts the optional parameters
  # @option opts [DateTime] :created_at_from 指定された日時以降に作成された取引を取得します。指定された日時に作成されたものも含まれます。 RFC3399の&#x60;date-time&#x60;(2019-04-01T10:36:43+09:00)で指定してください。
  # @option opts [DateTime] :created_at_to 指定された日時以前に作成された取引を取得します。指定された日時に作成されたものも含まれます。 RFC3399の&#x60;date-time&#x60;(2019-04-01T10:36:43+09:00)で指定してください。
  # @option opts [Date] :date_from 取引日が指定された日付以降の取引を取得します。指定された日付が取引日のものも含まれます。 RFC3399の&#x60;full-time&#x60;(2019-04-01)で指定してください。
  # @option opts [Date] :date_to 取引日が指定された日付以前の取引を取得します。指定された日付が取引日のものも含まれます。 RFC3399の&#x60;full-time&#x60;(2019-04-01&#x60;)で指定してください。
  # @option opts [String] :status 取引のステータスを指定します。未審査(&#x60;unexamined&#x60;)、審査通過(&#x60;passed&#x60;)、審査否決(&#x60;rejected&#x60;)、キャンセル済み(&#x60;canceled&#x60;)のいずれかを指定してください。
  # @option opts [String] :number 任意の取引の &#x60;number&#x60;を指定します。該当する取引がある場合、その一件のみが返却されます。
  # @option opts [String] :customer_id 任意の顧客IDを指定します。指定した顧客に対する取引が返却されます。
  # @option opts [String] :billing_id 任意の請求IDを指定します。指定した請求に含まれる取引が返却されます。
  # @option opts [String] :after 任意のリソースIDを指定します。追加日時の降順でこのIDのリソースよりも後のリソースを取得します。この時&#x60;after&#x60;で指定したIDのリソースは結果に含まれません。
  # @option opts [String] :before 任意のリソースIDを指定します。追加日時の降順でこのIDのリソースよりも前のリソースを取得します。この時&#x60;before&#x60;で指定したIDのリソースは結果に含まれません。
  # @option opts [Integer] :limit 取得したいリソースの最大件数を指定します。1~200の間の整数で指定してください。指定がない場合は20になります。
  # @return [InlineResponse2004]
  describe 'get_transactions_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
