=begin
#MF KESSAI REST API

#MF KESSAI REST API

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for Mfkessai::TransactionApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TransactionApi' do
  before do
    # run before each test
    @instance = Mfkessai::TransactionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TransactionApi' do
    it 'should create an instance of TransactionApi' do
      expect(@instance).to be_instance_of(Mfkessai::TransactionApi)
    end
  end

  # unit tests for transaction_cancel
  # cancel transaction
  # 取引をキャンセル
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [MfkTransaction]
  describe 'transaction_cancel test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for transaction_create
  # create transaction
  # 取引を登録
  # @param payload 
  # @param [Hash] opts the optional parameters
  # @return [MfkTransactionDetails]
  describe 'transaction_create test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for transaction_index
  # index transaction
  # 取引リストを取得
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page ページ番号
  # @option opts [Integer] :per_page 1ページあたりの件数
  # @return [MfkTransactions]
  describe 'transaction_index test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for transaction_show
  # show transaction
  # 取引IDを指定して取得
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [MfkTransaction]
  describe 'transaction_show test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
