=begin
#MF KESSAI API v2

#MF KESSAI REST API

The version of the OpenAPI document: 0.2.0
Contact: support@mfkessai.co.jp
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::InvoiceDeliveryMethod
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InvoiceDeliveryMethod' do
  before do
    # run before each test
    @instance = OpenapiClient::InvoiceDeliveryMethod.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InvoiceDeliveryMethod' do
    it 'should create an instance of InvoiceDeliveryMethod' do
      expect(@instance).to be_instance_of(OpenapiClient::InvoiceDeliveryMethod)
    end
  end
end
