=begin
#MF KESSAI API v2

#MF KESSAI REST API

The version of the OpenAPI document: 0.2.0
Contact: support@mfkessai.co.jp
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.1

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/account_transfer'
require 'openapi_client/models/amount_per_tax_rate_type'
require 'openapi_client/models/bank_transfer'
require 'openapi_client/models/billing'
require 'openapi_client/models/billing_unpaid'
require 'openapi_client/models/credit_facility'
require 'openapi_client/models/customer'
require 'openapi_client/models/customer_examination'
require 'openapi_client/models/customer_examination_payload'
require 'openapi_client/models/customer_payload'
require 'openapi_client/models/customer_payload_customer_examination'
require 'openapi_client/models/customer_payload_destination'
require 'openapi_client/models/deduction'
require 'openapi_client/models/deduction_tax'
require 'openapi_client/models/deduction_tax_free'
require 'openapi_client/models/deduction_taxable'
require 'openapi_client/models/deduction_taxable_posting'
require 'openapi_client/models/destination'
require 'openapi_client/models/destination_payload'
require 'openapi_client/models/error'
require 'openapi_client/models/inline_response200'
require 'openapi_client/models/inline_response2001'
require 'openapi_client/models/inline_response2002'
require 'openapi_client/models/inline_response2003'
require 'openapi_client/models/inline_response2004'
require 'openapi_client/models/inline_response2005'
require 'openapi_client/models/inline_response2006'
require 'openapi_client/models/inline_response2007'
require 'openapi_client/models/invoice_delivery_method'
require 'openapi_client/models/pagination'
require 'openapi_client/models/payment_method'
require 'openapi_client/models/payout'
require 'openapi_client/models/payout_transaction'
require 'openapi_client/models/tax_included_type'
require 'openapi_client/models/tax_rate_type'
require 'openapi_client/models/transaction'
require 'openapi_client/models/transaction_detail'
require 'openapi_client/models/transaction_detail_payload'
require 'openapi_client/models/transaction_payload'

# APIs
require 'openapi_client/api/billing_api'
require 'openapi_client/api/credit_facility_api'
require 'openapi_client/api/customer_api'
require 'openapi_client/api/customer_examination_api'
require 'openapi_client/api/destination_api'
require 'openapi_client/api/payout_api'
require 'openapi_client/api/payout_transaction_api'
require 'openapi_client/api/transaction_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
