=begin
#MF KESSAI REST API

#MF KESSAI REST API

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/create_transaction_by_examination_payload'
require 'swagger_client/models/customer_examination_payload'
require 'swagger_client/models/customer_payload'
require 'swagger_client/models/destination_payload'
require 'swagger_client/models/error'
require 'swagger_client/models/examination_detail_payload'
require 'swagger_client/models/examination_payload'
require 'swagger_client/models/mfk_credit_facility'
require 'swagger_client/models/mfk_customer'
require 'swagger_client/models/mfk_customer_examination'
require 'swagger_client/models/mfk_customers'
require 'swagger_client/models/mfk_destination'
require 'swagger_client/models/mfk_examination'
require 'swagger_client/models/mfk_examinations'
require 'swagger_client/models/mfk_transaction'
require 'swagger_client/models/mfk_transaction_details'
require 'swagger_client/models/mfk_transactions'
require 'swagger_client/models/pagination'
require 'swagger_client/models/transaction_detail'
require 'swagger_client/models/transaction_payload'

# APIs
require 'swagger_client/api/customer_api'
require 'swagger_client/api/destination_api'
require 'swagger_client/api/examination_api'
require 'swagger_client/api/ping_api'
require 'swagger_client/api/transaction_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
